title: Cole Boyer
theme: jekyll-theme-minimal
description: Seeking full time employment in the field of Information Technology.  Four years experience as a System Administrator.  Ten years experience with customer service and support.